version: '3.8'
services:
  next-store-ui:
    build:
      context: ../next-store-ui
      dockerfile: Dockerfile
    ports:
      - 80:3000
      - 3000:3000
      - 443:3000
    volumes:
      - ./data/nextjs:/app
    depends_on:
      - laravel-store-rest-api
    networks:
      - public

  laravel-store-rest-api:
    build:
      context: ../laravel-store-rest-api
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    volumes:
      - ./data/laravel:/app
    depends_on:
      - postgres
      - keydb
    networks:
      - public
      - private

  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: db_user
      POSTGRES_PASSWORD: db_pass
      POSTGRES_DB: store_db
    # ports:
    #   - 5432:5432
    volumes:
      - ./data/postgres-data:/var/lib/postgresql/data
    networks:
      - private

  keydb:
    image: eqalpha/keydb
    # ports:
    #   - 6379:6379
    volumes:
      - ./data/keydb-data:/data
    networks:
      - private

networks:
  public:
  private:

  